### ISSUE TITLE
[BUG] Unable to use ? 

### ISSUE THREAD

**Issue by Steelskinz** [ironmonk88/monks-chat-timer#2]
Unable to use /timer from the chat, however it works fine with Active Tiles. 
![image](https://user-images.githubusercontent.com/93941729/222884605-8cb36e90-d438-4235-b453-406518b06cce.png)
![image](https://user-images.githubusercontent.com/93941729/222884608-1b8e9d96-09c3-44ee-8098-fbe261f88e39.png)

Edit : Found the issue. Chat library was not updated for some reason.

**Comment by Crowguard** [comment]
@Steelskinz Do you have https://foundryvtt.com/packages/_chatcommands installed, updated, and active? That was someone else's problem that solved it.
