### ISSUE TITLE
/timer is not a valid command

### ISSUE THREAD

**Issue by plumppig** [ironmonk88/monks-chat-timer#5]
Whenever I attempt to use the /timer command it throws the error, "/timer is not a valid command..."

![Screenshot 2023-03-05 at 10 38 04 AM](https://user-images.githubusercontent.com/5460707/222976624-7e8aa12d-2bc9-4e89-8c0c-c269dff38213.png)

And here is the console log

![Screenshot 2023-03-05 at 10 38 16 AM](https://user-images.githubusercontent.com/5460707/222976634-da8765fa-2323-4afb-9e4a-7936bd5ba031.png)

**Comment by plumppig** [comment]
Looks like this is happening for me in the local version of Foundry only; same configuration in The Forge is working

**Comment by ironmonk108** [comment]
![image](https://user-images.githubusercontent.com/75920956/222985822-3230be2f-d7a3-47ff-8978-5ca8d12a74cd.png)

**Comment by plumppig** [comment]
![Screenshot 2023-03-05 at 2 16 46 PM](https://user-images.githubusercontent.com/5460707/222986591-c616e875-d7fe-4c5c-93fd-7ff0551899e7.png)

![Screenshot 2023-03-05 at 2 17 50 PM](https://user-images.githubusercontent.com/5460707/222986598-91c14230-001d-4f35-b66a-ef4d37e200ba.png)

**Comment by plumppig** [comment]
Looks like my local install is borked somehow... it's flagged as 1.4.0 in the install list, but the manage module list says it's beta1.0.0 (despite not being locked).  I'll close the ticket.
